### ISSUE TITLE
shell, Makefile: different colors for \<newline> and \<space>

### ISSUE THREAD

**Issue by singalen** [colorer/Colorer-schemes#119]
This would help to prevent a lot of silly errors.
`\<space><newline>` in not noticeable in far2l in `.sh` script now.

**Comment by ctapmex** [comment]
I didn't understand what was required, apparently not in the context. But @chpock claims to be fixed in https://github.com/colorer/Colorer-schemes/releases/tag/v1.2.0.36

**Comment by chpock** [comment]
In shell scripts it is possible to escape `<newline>` by backslash, and `<newline>` will not end the command, but it will continue on the next line. In this case, `<newline>` must be imidiatlly followed by backslash.

However, when there are spaces between backslash and `<newline>`, the `<newline>` is not escaped and command is not continue to the next line. Since, such spaces are usually not visible, it can be hard to understand why behaviour is not as expected.

i.e. @singalen asked to mark such spaces after backslash as an error:

![изображение](https://github.com/colorer/Colorer-schemes/assets/3234796/de5cb0c7-ecec-460b-8ac8-c53a636b3e4e)

**Comment by ctapmex** [comment]
ok/ 
fixed in https://github.com/colorer/Colorer-schemes/releases/tag/v1.2.0.36
